language: node_js

node_js:
  - 9

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn install

script:
- yarn build

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: rnoo